SIGN_PROFILES = {
    "aries": {
        "name": "Beran",
        "emoji": "♈️",
        "dates": "21. 3. – 20. 4.",
        "element": "Oheň",
        "planet": "Mars",
        "description": "Beran je znamení odvahy, akce a spontánnosti. Potřebuje výzvy, rychlost a prostor tvořit. Je přímý, čestný a často strhne ostatní svým elánem. Jeho úkolem je učit se zpomalit a najít klid uprostřed pohybu.",
        "strengths": ["Odvaha", "Přirozené vedení", "Energie", "Autenticita"],
        "growth": ["Trpělivost", "Naslouchání", "Citlivost k druhým"],
        "love_profile": "Beran miluje s ohněm v srdci. Je přímý a vášnivý, ale potřebuje partnera, který chápe jeho nezávislost. Pokud cítí důvěru, je oddaný a loajální.",
        "career_profile": "V práci vyniká jako inovátor a lídr. Potřebuje akci a smysl. Daří se mu ve vedení týmů, sportu, startupech a umění.",
        "health_profile": "Energie Berana je vysoká – potřebuje ji vybíjet pohybem. Pomáhá mu sport, běh nebo box. Když se unaví, měl by si dopřát klid a masáž hlavy.",
        "compatibility": {"best": ["Lev", "Střelec", "Blíženci"], "challenge": ["Rak", "Panna"]},
        "affirmations": ["Jdu s odvahou za svými cíli.", "Každý den mohu začít znovu.", "Síla ve mně plyne s klidem."],
        "famous": ["Lady Gaga", "Tomáš Baťa", "Emma Watson", "Robert Downey Jr."],
        "quote": "„Kde jiní čekají na znamení, Beran už běží.“",
    },
    "taurus": {
        "name": "Býk",
        "emoji": "♉️",
        "dates": "21. 4. – 21. 5.",
        "element": "Země",
        "planet": "Venuše",
        "description": "Býk je symbolem klidu, jistoty a smyslnosti. Miluje kvalitu, krásu a stabilitu. Umí si užívat život i pracovat s odhodláním. Jeho síla je v trpělivosti a vytrvalosti.",
        "strengths": ["Stabilita", "Loajalita", "Praktičnost", "Smysl pro krásu"],
        "growth": ["Otevřenost změnám", "Flexibilita", "Neulpívání"],
        "love_profile": "Býk miluje pomalu, ale hluboce. Potřebuje důvěru, jistotu a dotek. Vztah bere vážně a dává do něj celé srdce.",
        "career_profile": "V práci je spolehlivý a důsledný. Daří se mu v oblasti designu, financí, gastronomie nebo přírody.",
        "health_profile": "Býk potřebuje pravidelný rytmus, dobré jídlo a kvalitní spánek. Klid nachází v přírodě, zahradě nebo při vaření.",
        "compatibility": {"best": ["Rak", "Panna", "Kozoroh"], "challenge": ["Lev", "Vodnář"]},
        "affirmations": ["Jdu vpřed s klidem.", "Důvěřuji životnímu rytmu.", "Vše, co potřebuji, už mám v sobě."],
        "famous": ["Adele", "David Beckham", "William Shakespeare", "George Clooney"],
        "quote": "„Trpělivost není slabost, ale síla v klidu.“",
    },
    "gemini": {
        "name": "Blíženci",
        "emoji": "♊️",
        "dates": "22. 5. – 21. 6.",
        "element": "Vzduch",
        "planet": "Merkur",
        "description": "Blíženci jsou zvídaví komunikátoři a přirození učitelé. Milují rozmanitost, myšlenky a konverzaci. Umí být lehcí jako vítr i hlubocí, když se zastaví.",
        "strengths": ["Komunikace", "Zvědavost", "Přizpůsobivost", "Vtip"],
        "growth": ["Soustředění", "Dotažení věcí", "Upřímnost k sobě"],
        "love_profile": "Ve vztahu potřebují intelektuální jiskru. Milují flirt, smích a sdílení nápadů. Neznášejí nudu – vztah musí dýchat.",
        "career_profile": "Daří se jim tam, kde se mluví, píše nebo propojuje. Jsou skvělí novináři, marketingoví specialisté nebo učitelé.",
        "health_profile": "Blíženci potřebují duševní stimul i tělesný pohyb. Pomáhá jim jóga, tanec nebo turistika.",
        "compatibility": {"best": ["Váhy", "Vodnář", "Beran"], "challenge": ["Panna", "Ryby"]},
        "affirmations": ["Mluvím pravdivě a s lehkostí.", "Učím se v každé situaci.", "Můj život je hra inspirace."],
        "famous": ["Angelina Jolie", "Johnny Depp", "Karel Hynek Mácha"],
        "quote": "„Slova jsou můj tanec – myšlenky mým domovem.“",
    },
    "cancer": {
        "name": "Rak",
        "emoji": "♋️",
        "dates": "22. 6. – 22. 7.",
        "element": "Voda",
        "planet": "Měsíc",
        "description": "Rak je citlivé, empatické a ochranitelské znamení. Miluje domov, rodinu a emocionální jistotu. Jeho síla spočívá v empatii a hluboké intuici.",
        "strengths": ["Empatie", "Laskavost", "Věrnost", "Citlivost"],
        "growth": ["Nezávislost", "Sebehodnota", "Odpoutání od minulosti"],
        "love_profile": "Ve vztahu dává všechno. Miluje naplno, chrání a pečuje. Potřebuje citové bezpečí a partnera, který ho chápe.",
        "career_profile": "Raci jsou výborní terapeuti, pečovatelé, kuchaři nebo umělci. Daří se jim tam, kde cítí smysl.",
        "health_profile": "Potřebují vnitřní klid. Pomáhá jim meditace, koupel, voda, moře. Když jsou přetíženi, stahují se do ulity.",
        "compatibility": {"best": ["Býk", "Panna", "Ryby"], "challenge": ["Beran", "Váhy"]},
        "affirmations": ["Mám právo na klid.", "Moje citlivost je darem.", "Důvěřuji své intuici."],
        "famous": ["Dalajláma", "Tom Hanks", "Meryl Streep", "Frida Kahlo"],
        "quote": "„Cit není slabost, ale kompas duše.“",
    },
    "leo": {
        "name": "Lev",
        "emoji": "♌️",
        "dates": "23. 7. – 22. 8.",
        "element": "Oheň",
        "planet": "Slunce",
        "description": "Lev je znamení záře, kreativity a odvahy. Miluje být vidět, ale hlavně miluje dávat světlo ostatním. Když věří sobě, stává se inspirací.",
        "strengths": ["Sebevědomí", "Velkorysost", "Tvořivost", "Věrnost"],
        "growth": ["Pokora", "Naslouchání", "Přijetí kritiky"],
        "love_profile": "Lev miluje velkolepě. Potřebuje obdiv, ale dává skutečné teplo. Je věrný a romantický, když se cítí uznávaný.",
        "career_profile": "Daří se mu v rolích, kde může tvořit, vést nebo vystupovat. Skvělý herec, manažer, motivátor.",
        "health_profile": "Potřebuje srdcem milovat, smát se, tančit. Sílu čerpá z radosti a slunce.",
        "compatibility": {"best": ["Beran", "Střelec", "Váhy"], "challenge": ["Býk", "Štír"]},
        "affirmations": ["Zářím přirozeně.", "Láska ve mně posiluje druhé.", "Dávám i přijímám srdcem."],
        "famous": ["Barack Obama", "Madonna", "Jennifer Lopez", "Mick Jagger"],
        "quote": "„Když svítíš sám, rozsvítíš i ostatní.“",
    },
    "virgo": {
        "name": "Panna",
        "emoji": "♍️",
        "dates": "23. 8. – 22. 9.",
        "element": "Země",
        "planet": "Merkur",
        "description": "Panna je precizní, vnímavá a pečující. Má dar analýzy i služby. Touží po dokonalosti, ale učí se, že krása je v jednoduchosti.",
        "strengths": ["Pečlivost", "Pomoc druhým", "Praktičnost", "Rozum"],
        "growth": ["Přijetí nedokonalosti", "Uvolnění", "Sebepřijetí"],
        "love_profile": "Panna miluje tiše, ale oddaně. Vyjadřuje lásku činy, ne slovy. Potřebuje jistotu, loajalitu a klid.",
        "career_profile": "Daří se jí v organizaci, zdravotnictví, vědě, výuce. Je zodpovědná a spolehlivá.",
        "health_profile": "Potřebuje rovnováhu mezi péčí o druhé a o sebe. Uklidňuje ji rutina a čistota prostoru.",
        "compatibility": {"best": ["Býk", "Kozoroh", "Rak"], "challenge": ["Blíženci", "Střelec"]},
        "affirmations": ["Jsem dost taková, jaká jsem.", "Dělám věci s láskou.", "Dokonalost je v jednoduchosti."],
        "famous": ["Beyoncé", "Keanu Reeves", "Agatha Christie"],
        "quote": "„Řád přináší klid a klid přináší moudrost.“",
    },
        "libra": {
        "name": "Váhy",
        "emoji": "♎️",
        "dates": "23. 9. – 23. 10.",
        "element": "Vzduch",
        "planet": "Venuše",
        "description": "Váhy jsou ztělesněním harmonie, krásy a rovnováhy. Mají silný smysl pro spravedlnost, estetiku a diplomacii. Potřebují klidné prostředí, kde mohou rozvíjet vztahy, umění i myšlenky. Jejich kouzlo je v přirozené eleganci.",
        "strengths": ["Takt", "Elegance", "Společenskost", "Spravedlnost"],
        "growth": ["Rozhodnost", "Sebejistota", "Nezávislost"],
        "love_profile": "Váhy milují jemně a s citem. Jsou romantické duše, které hledají rovnováhu a porozumění. Milují estetiku, smyslnost a dialog.",
        "career_profile": "Skvělí diplomaté, umělci, právníci nebo designéři. Umí spojovat lidi a vyvažovat konflikty.",
        "health_profile": "Váhy potřebují krásu a klid. Pomáhá jim tanec, hudba, procházky v přírodě. Jejich tělo reaguje na stres citlivě – potřebují vnitřní mír.",
        "compatibility": {"best": ["Blíženci", "Lev", "Vodnář"], "challenge": ["Rak", "Kozoroh"]},
        "affirmations": ["Žiji v rovnováze.", "Moje harmonie inspiruje ostatní.", "Láska je můj přirozený stav."],
        "famous": ["Mahatma Gándhí", "Kim Kardashian", "Catherine Zeta-Jones", "John Lennon"],
        "quote": "„Krása vzniká tam, kde vládne rovnováha.“",
    },

    "scorpio": {
        "name": "Štír",
        "emoji": "♏️",
        "dates": "24. 10. – 22. 11.",
        "element": "Voda",
        "planet": "Pluto",
        "description": "Štír je hluboký, intenzivní a proměňující. V jeho nitru je síla, vášeň i tajemství. Touží po pravdě a autentičnosti. Je loajální, když miluje, a nebojí se ponořit do hlubin emocí.",
        "strengths": ["Intuice", "Odvaha", "Hloubka", "Loajalita"],
        "growth": ["Důvěra", "Odpouštění", "Přijetí lehkosti"],
        "love_profile": "Štír miluje s vášní. Je citlivý, ale skrývá to. Potřebuje partnera, který zvládne jeho intenzitu a neuhne před emocemi.",
        "career_profile": "Daří se mu tam, kde může zkoumat hloubku – psychologie, výzkum, lékařství, umění. Když věří svému daru, dokáže proměňovat ostatní.",
        "health_profile": "Potřebuje klid, regeneraci a rovnováhu. Pomáhá mu voda, sauna, meditace a upřímné rozhovory.",
        "compatibility": {"best": ["Rak", "Ryby", "Kozoroh"], "challenge": ["Lev", "Vodnář"]},
        "affirmations": ["Síla je v hloubce.", "Každý konec je začátek.", "Důvěřuji procesu proměny."],
        "famous": ["Pablo Picasso", "Katy Perry", "Ryan Gosling", "Marie Curie"],
        "quote": "„Kdo se nebojí tmy, objeví světlo.“",
    },

    "sagittarius": {
        "name": "Střelec",
        "emoji": "♐️",
        "dates": "23. 11. – 21. 12.",
        "element": "Oheň",
        "planet": "Jupiter",
        "description": "Střelec je dobrodruh, vizionář a filozof. Miluje svobodu, poznání a humor. Je optimistický a otevřený, i když občas trochu netrpělivý. Jeho duše touží po pravdě a autenticitě.",
        "strengths": ["Optimismus", "Upřímnost", "Filozofický pohled", "Svobodomyslnost"],
        "growth": ["Zodpovědnost", "Trpělivost", "Citlivost k druhým"],
        "love_profile": "Střelec potřebuje vztah, který mu dává prostor dýchat. Miluje dobrodružství a partnera, který sdílí jeho humor a zvídavost.",
        "career_profile": "Daří se mu ve vzdělávání, cestování, médiích nebo obchodu. Potřebuje smysl a vizi.",
        "health_profile": "Miluje pohyb – běh, cyklistiku, jízdu na koni. Pomáhá mu příroda a otevřený prostor.",
        "compatibility": {"best": ["Lev", "Beran", "Vodnář"], "challenge": ["Panna", "Rak"]},
        "affirmations": ["Můj život je cesta poznání.", "Svoboda a radost jsou můj kompas.", "Směji se a rostu."],
        "famous": ["Taylor Swift", "Brad Pitt", "Winston Churchill", "Mark Twain"],
        "quote": "„Kam míříš, tam půjde celý tvůj svět.“",
    },

    "capricorn": {
        "name": "Kozoroh",
        "emoji": "♑️",
        "dates": "22. 12. – 20. 1.",
        "element": "Země",
        "planet": "Saturn",
        "description": "Kozoroh je vytrvalý, ambiciózní a disciplinovaný. Stoupá po svých horách trpělivě a jistě. Jeho vnitřní síla je obrovská – staví mosty, tvoří stabilitu a inspiruje ostatní odpovědností.",
        "strengths": ["Disciplína", "Vytrvalost", "Spolehlivost", "Zralost"],
        "growth": ["Flexibilita", "Uvolnění", "Radost ze života"],
        "love_profile": "Kozoroh miluje tiše, ale hluboce. Prokazuje lásku skutky, ne slovy. Potřebuje stabilní vztah, kde vládne důvěra.",
        "career_profile": "Vyniká v manažerských, analytických a organizačních rolích. Umí nést odpovědnost a vytvářet strukturu.",
        "health_profile": "Kozoroh potřebuje rovnováhu mezi prací a odpočinkem. Pomáhá mu hory, chůze a dechová cvičení.",
        "compatibility": {"best": ["Býk", "Panna", "Štír"], "challenge": ["Beran", "Váhy"]},
        "affirmations": ["Krok za krokem tvořím svou cestu.", "Síla je v klidu a vytrvalosti.", "Odpočinek je součástí úspěchu."],
        "famous": ["Michelle Obama", "Jim Carrey", "Isaac Newton", "David Bowie"],
        "quote": "„Trpělivost staví hory.“",
    },

    "aquarius": {
        "name": "Vodnář",
        "emoji": "♒️",
        "dates": "21. 1. – 18. 2.",
        "element": "Vzduch",
        "planet": "Uran",
        "description": "Vodnář je vizionář, který přináší změnu. Miluje svobodu, originalitu a nové myšlenky. Je nezávislý, lidský a přemýšlivý. Touží po lepším světě a věří v sílu komunity.",
        "strengths": ["Originalita", "Humanita", "Inteligence", "Svobodomyslnost"],
        "growth": ["Trpělivost", "Propojení s emocemi", "Realizace nápadů"],
        "love_profile": "Vodnář miluje svobodně, ale upřímně. Potřebuje partnera, který mu dá prostor a respektuje jeho jedinečnost.",
        "career_profile": "Daří se mu v technologiích, inovacích, umění a komunitních projektech. Je myslitel a reformátor.",
        "health_profile": "Pomáhá mu vzduch, dech, kreativní aktivity a kontakt s lidmi. Měl by se vyhýbat izolaci.",
        "compatibility": {"best": ["Blíženci", "Váhy", "Střelec"], "challenge": ["Býk", "Štír"]},
        "affirmations": ["Jsem svobodný v myšlení i v srdci.", "Mé nápady mění svět.", "Respektuji svou jedinečnost."],
        "famous": ["Charles Darwin", "Oprah Winfrey", "Mozart", "Ellen DeGeneres"],
        "quote": "„Budoucnost začíná myšlenkou.“",
    },

    "pisces": {
        "name": "Ryby",
        "emoji": "♓️",
        "dates": "19. 2. – 20. 3.",
        "element": "Voda",
        "planet": "Neptun",
        "description": "Ryby jsou snílci, umělci a empati. Cítí hlouběji než ostatní a mají přirozený dar intuice. Potřebují klid, krásu a propojení s vnitřním světem. Jejich síla je v soucitu.",
        "strengths": ["Empatie", "Intuice", "Kreativita", "Citlivost"],
        "growth": ["Hranice", "Realismus", "Sebepéče"],
        "love_profile": "Ryby milují beze zbytku. Jsou romantické a oddané, ale potřebují partnera, který je uzemní. Láska pro ně znamená splynutí duší.",
        "career_profile": "Daří se jim v umění, hudbě, lékařství a charitě. Jsou vynikající vizionáři a pomáhají druhým.",
        "health_profile": "Ryby musí pečovat o svou energii – mají sklon přebírat emoce druhých. Pomáhá jim meditace, plavání a pobyt u vody.",
        "compatibility": {"best": ["Rak", "Štír", "Kozoroh"], "challenge": ["Blíženci", "Střelec"]},
        "affirmations": ["Můj cit je mou silou.", "Důvěřuji své intuici.", "Mír začíná ve mně."],
        "famous": ["Albert Einstein", "Rihanna", "Steve Jobs", "Kurt Cobain"],
        "quote": "„V tichu svých emocí nacházím pravdu.“",
    },

}
